services:

  app:
    environment:
      - VITE_SOCKET_URL=http://socketio:3000

  cypress:
    image: cypress/included:latest
    environment:
      - CYPRESS_baseUrl=http://app:5173
    depends_on:
      - app
    volumes:
      - ./client:/e2e
      - /tmp/.X11-unix:/tmp/.X11-unix
    working_dir: /e2e
    entrypoint: ["cypress", "run"]
