version: '3'

services:

  socketio:
    image: node:20
    ports:
      - '3000:3000'
    working_dir: /app
    volumes:
      - ./server:/app
    command: node server.js

  app:
    image: node:20
    ports:
      - '5173:5173'
    working_dir: /app
    environment:
      - VITE_SOCKET_URL=http://localhost:3000
    volumes:
      - ./client:/app
    command: npm run dev -- --host
